project_id = "ybxumvrjngpqnsleyxga"

[functions.crm-create-instance]
verify_jwt = true

[functions.crm-get-qrcode]
verify_jwt = true

[functions.crm-disconnect-instance]
verify_jwt = true

[functions.crm-send-message]
verify_jwt = true

[functions.crm-get-messages]
verify_jwt = true

[functions.crm-webhook]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.create-consultant]
verify_jwt = true

[functions.crm-check-connection]
verify_jwt = true

[functions.crm-repair-connection]
verify_jwt = true
